### ISSUE TITLE
dbc supports either can_fd or j1939; mix seems not possible [dbc]

### ISSUE THREAD

**Issue by rpkvt** [ebroecker/canmatrix#242]
Hello!
I'm writing software to create dbc files using canmatrix.  I'm using version f9b84b834b1b93d849823a01d4bcea33b01f8866

When I run my software I generated a dbc that looks something like this:

VERSION "created by canmatrix"

NS_ :

BS_:

BU_: 

BO_ 2566849152 Node415_0xff02: 14 Vector__XXX
 SG_ ch10 : 7|32@0- (1,0) [-2147483648|2147483647] "" Vector__XXX
 SG_ ch11 : 39|32@0- (1,0) [-2147483648|2147483647] "" Vector__XXX
 SG_ ch12 : 71|32@0- (1,0) [-2147483648|2147483647] "" Vector__XXX
 SG_ Padding_0 : 103|8@0+ (1,0) [0|255] "" Vector__XXX
 SG_ Padding_1 : 111|8@0+ (1,0) [0|255] "" Vector__XXX

BA_DEF_ BO_ "VFrameFormat" ENUM "StandardCAN","ExtendedCAN","StandardCAN_FD","ExtendedCAN_FD","J1939PG";
BA_DEF_ "ProtocolType" STRING;

BA_ "ProtocolType" "J1939";

BA_ "VFrameFormat" BO_ 2566849152 4;

Which gets interpreted like this:
![image](https://user-images.githubusercontent.com/33731793/48166028-5c484c00-e2b5-11e8-9ff6-50ab3e33e9c1.png)

Which doesn't seem to tell the receiving system how to parse the incoming datastream:
![image](https://user-images.githubusercontent.com/33731793/48166117-97e31600-e2b5-11e8-8325-42df955d7bd6.png)

I have an example dbc file which looks like this (and seems to be parsed correctly):
![image](https://user-images.githubusercontent.com/33731793/48166096-869a0980-e2b5-11e8-81e3-a6b24567e266.png)

If I change a line from the code above to this (changed the 4 to a 3):
BA_ "VFrameFormat" BO_ 2566849152 3;

Then the software seems to interpret it correctly:
![image](https://user-images.githubusercontent.com/33731793/48166180-ce209580-e2b5-11e8-8468-9407d5cf7107.png)

The software shows the values of individual variables: 
![image](https://user-images.githubusercontent.com/33731793/48166172-c234d380-e2b5-11e8-8ae7-23f2fa0f9d5b.png)

My question is how do I get Canmatrix to output a 3 instead of a 4?

Here are the code blocks I wrote for creating frames and making the DBC:

```python
    def CreateFrame(self,msgName,pgn,priority=0x06,message=""):
        if len(self.signals) == 0:
            return
        frame = canmatrix.Frame(    msgName,
                                    j1939_pgn=pgn,
                                    j1939_prio=priority,
                                    j1939_source=self.src_addr,
                                    comment=message
                                )
        for sig in self.signals:
            frame.addSignal(sig)

        self.cm.frames.addFrame(frame)
        #self.cm.addFrame(frame)
        self.startBit = 0
        self.signals.clear()



    def CommitDBC(self,filename):
        self.cm.recalcDLC("force")

        print(canmatrix.formats.supportedFormats)

        # save dbc
        canmatrix.formats.dumpp({"": self.cm}, filename)
```

Thanks,
Rich

**Comment by ebroecker** [comment]
Hi @rpkvt ,
Thanks for your Report.

I cannot reproduce the views in candb. 
You are creating a J1939-dbc. 
My knowledge about them is very limited. Issues witch canmatrix regarding J1939 are very likely.

In my eyes a VFrameFormat 'J1939PG' (which is '4') looks right. A '3' represents 'ExtendedCAN_FD'. 
But if I open the dbc, and do some not relevant changes, and save it again, a '3' is set. 
Seems you are right.

Another idea:
candb++ expects the enumeration to be like this:
```
"VFrameFormat" ENUM  "StandardCAN","ExtendedCAN","reserved","J1939PG"
```
and does not honor our self made enumeration. 
A quick check seems to verifiy my idea.

the code responsible for the frame-format (dbc attribute "VFrameFormat") is here: 
https://github.com/ebroecker/canmatrix/blob/development/src/canmatrix/dbc.py#L81-L101

I think, it is not possible to create a dbc with FD and J1939 mixed, because candb++ does not honor it. I'll have to investigate a bit further.

a quick fix for you could be to exchange the line https://github.com/ebroecker/canmatrix/blob/development/src/canmatrix/dbc.py#L88:
```
"VFrameFormat" ENUM  "StandardCAN","ExtendedCAN","StandardCAN_FD","J1939PG","ExtendedCAN_FD";
```
Positions of "J1939PG" and "ExtendedCAN_FD" are switched.

**Comment by rpkvt** [comment]
@ebroecker 
Thanks for your response.  Yeah, I was wondering if that was the problem. Switching the two seemed to do the trick.
