### ISSUE TITLE
IndexError: list index out of range canconvert from .dbc to xlsx

### ISSUE THREAD

**Issue by TheBossAmine** [ebroecker/canmatrix#726]
File "C:\Users\Axxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\canmatrix\canmatrix.py", line 2317, in enum_attribs_to_values
    frame.attributes[define] = self.frame_defines[define].values[int(frame.attributes[define])]
IndexError: list index out of range

python version 3.10.10

Hello, I am trying to convert my dbc file into an xlsx format, the code seems to be crashing each time.

Thank you.

**Comment by ebroecker** [comment]
Hi @TheBossAmine 

Some value which is set in one frame is not in the corresponding value-table (ENUM).
I think - but I'm not sure - this could be an error in your dbc.  Is candb++ fine with the dbc?

You are not able to share the dbc (maybe as pn?).

If not, maybe I'll create a special-debug-version for you, to find out the root cause...

**Comment by ebroecker** [comment]
no news here ... - may be fixed already... - if not - please reopen!
